added feature to save macros
martin2250/OpenCNCPilot pull request #114
Opened 2019-11-25 23:56 UTC by beckmx

This feature enables the creation of a file called "macros.txt" that allows easy transportation between clients, computers and users

2019-11-26 17:31 UTC, beckmx commented
Ok, I am seeing bad spaces being introduced :s

2019-11-26 21:01 UTC, martin2250 requested changes
Hi @beckmx,

first of all thank you for submitting the first pull request! The current implementation of storing macros is pretty bad, so the idea of moving macros to a more user-accessible file is great. That said, I won't merge this in the current implementation.

The changes to the start/pause buttons (in my opinion) are not at all obvious to the user and might lead to the machine doing unintentional things. I want the general machine interface to be as much of a direct interface to raw GRBL as possible. Also the blocking sleep function would make the 
window unresponsive.

The json file format you propose doesn't contain any labels. If we do go for JSON (which is a good format for this IMO), why not actually label things and make it more clear to the user what the boolean in the tuple actually means?

The real-time spindle speed is also a good addition. I don't use the PWM output of GRBL, so I never really considered it.

In general you should split up changes to different parts of the code into multiple pull requests, so it is clear what actually changes. There are many changes which are not at all clear from the title. This also includes the version number change, which shouldn't be part of a general 'feature pull request' anyways.

Please don't be discouraged by my comments, I really like the idea of this macro file and I'll gladly merge a proper implementation of this :)

Cheers,
Martin

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.FileTab.cs
> +            machine.SendLine("M3");
This has to go. There are also use cases where the spindle isn't supposed to run. For example a drag engraver or a measurement routine.

The idea is good though, I've already thought about scanning the file for M3s and asking for confirmation if there is a G1 before M3.

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.FileTab.cs
> +            machine.SendLine("M5");
This as well. I'm not sure how well the machine control class handles the switch from file mode to single line mode. The pause button should only make OpenCNCPilot stop sending lines to GRBL, if there is an immediate need to stop the machine and spindle, the e-stop or soft reset should be used.

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.MachineStatus.cs
> +			RunSpindleOvr.Text = $"{machine.SpindleOverride} RPM {machine.SpindleSpeedRealtime}%";
Isn't there already a label in the status bar for real time feed rate? (I'm actually asking, I haven't used OCP for much too long now). If there is, I feel the spindle speed should be placed there as well.

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +                    string json = r.ReadToEnd();
why not use File.ReadAllText? r isn't used anywhere else in that using block

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +            string json = JsonConvert.SerializeObject(Macros.ToArray());
there are two things wrong with this:
1) it is duplicated [here](https://github.com/martin2250/OpenCNCPilot/pull/114/files#diff-9d4c26b8abc11103a574f98937249eabR110)
2) macros.txt is placed in the working directory, which could be anywhere, including the desktop. The path should be either configurable or at least be placed in %appdata% or something

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.StatusBar.cs
> +            machine.SendLine("M5");
again, feed hold should only do what it says, nothing more

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/OpenCNCPilot.csproj
> +  </ItemGroup>
are the changes to this file (apart from adding the json dependency) intentional or just the result of using a newer version of VS? (I'm fine with leaving them in, if it would happen to me as well)

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.5.8.0")]
huh, what happened to 1.5.7?

2019-11-26 21:01 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +                Debug.WriteLine("FILE CLEAN");
I feel this should be happening at the same time as upgrading the settings file. See 61dc5efe9b77ee108e2dc46539508d867f64ff4a.

2019-11-26 21:14 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.FileTab.cs
> +            machine.SendLine("M3");
I see, well, if you dont send an "S" command, it won't start at all, this only applies when we previously had a definition for "S", for the files not containing "S" speed, it just doesnt do anything, this comes more from the preprocessor used.

2019-11-26 21:19 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.FileTab.cs
> +            machine.SendLine("M5");
actually my main change (the one I wanted originally) was this :p, sometimes when I am milling and I pause either by "Pausing" or by "Holding" the spindle keeps rotating and I had another two macros for stopping it or restarting it, this happens a lot when you have a "woodpecker" board, the infamous 3018, it keeps rotating

2019-11-26 21:19 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.MachineStatus.cs
> +			RunSpindleOvr.Text = $"{machine.SpindleOverride} RPM {machine.SpindleSpeedRealtime}%";
I haven't seen it, that's why I added it, I agree with you on the other change

2019-11-26 21:21 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +                    string json = r.ReadToEnd();
good point

2019-11-26 21:24 UTC, beckmx commented on OpenCNCPilot/OpenCNCPilot.csproj
> +  </ItemGroup>
I am using the VS2019 but I believe is there because of the json usage imported by the dependency

2019-11-26 21:25 UTC, beckmx commented on OpenCNCPilot/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.5.8.0")]
I sent 2 PR, the first one did contain 1.5.7 but today I sent this today, it overrode the first change

2019-11-26 21:26 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +                Debug.WriteLine("FILE CLEAN");
this can be erased, I forgot to erased it

2019-11-26 21:32 UTC, beckmx commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +            string json = JsonConvert.SerializeObject(Macros.ToArray());
1. agreed
2. that's the thing, most of CAD users use the apps more like a transportable binary, I would partially agree on the appdata solution but again, this discourages users to have several versions of the app, for instance I still have your previous binaries separated

2019-11-27 10:59 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.FileTab.cs
> +            machine.SendLine("M3");
Yes it does if GRBL was compiled without PWM output, like on my machine

2019-11-27 11:02 UTC, martin2250 commented on OpenCNCPilot/MainWindow.xaml.Macros.cs
> +            string json = JsonConvert.SerializeObject(Macros.ToArray());
To make OpenCNCPilot portable, all other settings should be transferred to json as well. This hard-coded approach just isn't great. How about having %appdata% as the default path but also looking in $PWD for an additional 'portable' macros file?

2019-11-30 06:32 UTC, closed without merging