G28 and G30 implementation
martin2250/OpenCNCPilot pull request #169
Opened 2022-07-12 16:52 UTC by Paciente8159

- recognizes G28 and G30 (values of G28 and G30 are read from $# command)
- this implementations can be extended to other non modal commands and G54-G59.3 coordinate system
- minor fixes to µCNC settings codes

This addresses issue #166 I believe.

2022-07-13 07:32 UTC, martin2250 commented
Hi,

thank you very much! Unfortunately, I won't get around to test this in the next month (handing in my thesis in 3 weeks), but I'm looking forward to merging this if everything is ok :)

Cheers!
Martin

2022-07-13 08:53 UTC, Paciente8159 commented
No problem. This is kind of an incomplete but functional code implementation.

This for example does not take in account changes to the G28/G30 coordinates made with manual commands G28.1/G30.1 (Grbl flavored) or G10 (for coordinates system).
The obvious solution would be to send another $# command after one of these commands, so the system updates the coordinates, and possibly force a redraw of the path.
Never the less this should not common since these coordinate systems are usually defined prior to running the program.

From an initial point of view it should be able to represent the intermediate (1 or 2 depending on the syntax) fast move types generated by the G28/G30 commands in the middle of the path.

2022-07-13 11:35 UTC, martin2250 commented
> Never the less this should not common since these coordinate systems are usually defined prior to running the program.

Not in my workflow, I usually open the file first and then set my coordinate system origin. Not sure how it currently reacts to that, but if this could lead to mistakes being made, the auto-update feature should be implemented before this makes it into `main`

2022-07-13 14:00 UTC, Paciente8159 commented
> Not in my workflow, I usually open the file first and then set my coordinate system origin. Not sure how it currently reacts to that, but if this could lead to mistakes being made, the auto-update feature should be implemented before this makes it into `main`

When I say coordinate system I mean changing the G28/G30 location. Usually G28/G30 are set once and are never changed. Home is a fixed absolute position in the machine and unless you change the endstop positions or the home aboslute position itself they should not change ever.

Currently the code does not do anything with G54-G59.3 coordinates but even those tipically are set via G10 and in the program you switch between them using the G54-G59.3 commands.

Even if it did currently OpenCNCPilot displays the path of the part in relative coordinates not absolute (I believe).

Actually reflecting on this matter I wonder if the G28/G30 is represented relative to the absolute position or the relative position (to the set origine at that point) in the parser?

2022-10-03 08:01 UTC, martin2250 requested changes
Hi, sorry this took so long. I just read up on what G28/G30 is supposed to do exactly. With your implementation, a G28 is converted into two G0s. I think it would be better if the G28 was passed along to the controller as-is.  
First of all: what do you want to archive with this PR? Are you just concerned with the toolpath preview and/or the code that is emitted when using the editing functions?
If you're ok with not having the G28 appear in the preview, this could be implemented similar to what I started to do in the passthrough branch: https://github.com/martin2250/OpenCNCPilot/commit/6614e5a4ad39b34a005b2f35218a11dfed1f5e56
This implementation just stores unknown commands as strings and puts them back in the outputted gcode as they were. The preview model would have to be adjusted by making the position undefined again, as the machine position after the G28 could be anywhere (assuming no knowledge of the G28 position).

If you want, I can try to get the "passthrough" solution to work, but no promises as to when it will be done :/

2022-10-03 08:01 UTC, martin2250 commented on OpenCNCPilot/Communication/Machine.cs
> +								this.G28Position = Vector3.Parse(coords);
should be G30Position?

2022-10-03 08:01 UTC, martin2250 commented on OpenCNCPilot/GCode/GCodeParser.cs
> +					if (param == 28 || param == 30)
we could also handle G53 here, right?

2022-10-03 08:01 UTC, martin2250 commented on OpenCNCPilot/GCode/GCodeParser.cs
> +						Line homemotion = new Line();
Wait... so you're breaking up a G28 into two separate G1? This means that when the GCode is re-emitted, the G28 is no longer present?
I have to be honest, I'm not ok with that... The default behavior for OpenCNCPilot is to pass through any commands that are not handled fully properly. And since I wouldn't consider this "proper" handling, I expect that the G28 would be passed to the output just as it was...

2022-10-03 09:35 UTC, Paciente8159 commented
This will be a long answer.

Yes G28 and G30 are only there for representation. This might be useful to detect some sort of collision maybe???
I'm okay with only being pass through. I can navigate fairly well through C# but you have a lot more depth of knowledge of the code so I that was the way I found to represent the G28/G30 conversion. Representing it with another color might be a solution but I did not found a way to do that.
What it says is that G28/G30 will make the tool travel to a stored home position (in machine coordinates). I the G28/G30 has also coordinates it will travel to that point first (working) and then to the home position.

Here is the definition of the G28/G30 from the NIST.

**3.5.8 Return to Home — G28 and G30**
Two home positions are defined (by parameters 5161-5166 for G28 and parameters 5181-5186 for
G30). The parameter values are in terms of the absolute coordinate system, but are in unspecified
length units.
To return to home position by way of the programmed position, program G28 X… Y… Z… A…
B… C… (or use G30). All axis words are optional. The path is made by a traverse move from the
current position to the programmed position, followed by a traverse move to the home position. If
no axis words are programmed, the intermediate point is the current point, so only one move is
made.

About the G53 and G54..G59.3 its a matter of representation.
Currently OpenCNCPilot treats all code in working coordinates and not machine coordinates. Let me explain.

Let's say you want you have a GCode that does one piece and then move the tool to the side and set a G92 or switch the working coordinate system (from G54 to G55 for example) and run the exact same GCode to reproduce a second, identical piece.

Currently OpenCNCPilot represents both pieces in the same place making the path indistinguishable.
Here is an example:
This code makes a square then makes a second square next to the first one.
```
G90G21G54M48
G0X0Y0Z0
(SQUARE)
F1000
G1X10
Y10
X0
Y0
(OFFSET)
G92X-10Y0Z0
G0X0Y0Z0
(SQUARE)
G1X10
Y10
X0
Y0
M2
```

Because OpenCNCPilot ignores G92 or any G54...G59.3 coordinates the square paths are represented overlapped and not what you really will get when the job runs.

2022-10-03 09:51 UTC, Paciente8159 commented on OpenCNCPilot/GCode/GCodeParser.cs
> +					if (param == 28 || param == 30)
G53 is machine coordinates. Since OpenCNCPilot already ignores all G92 and G54..G59.3 everything is represented like G53 was always active.

2022-10-03 09:54 UTC, Paciente8159 commented on OpenCNCPilot/GCode/GCodeParser.cs
> +						Line homemotion = new Line();
This was my solution based on the knowledge I get from OpenCNCPilot's code. I'm doing a bit like I do in µCNC for canned cycles. G28/G30 and canned cycles are (mostly at least) a series of simpler GCodes packed in a single command.

I understand that you think this is not the best solution. Mayby converting them into a new type of motion and representing them with a new color??

2022-10-03 10:31 UTC, Paciente8159 commented on OpenCNCPilot/Communication/Machine.cs
> +								this.G28Position = Vector3.Parse(coords);
You are right.

2022-10-04 19:29 UTC, martin2250 commented
we have two ways to go about G28/G30:
#### passthrough
This would be simple to implement but the preview wouldn't show anything. We could add some sort of "motion detection", so if the command in this line can move the machine, the preview model is cut at this point.
we could also add indicators to the places where the previewed toolpath starts and ends, which mean "the machine will leave the work area" and otherwise.
```
G0 X0 Y0 Z0 ; this establishes a known position
G1 X10          ; this is shown in preview (red indicator at the end of this preview line)
G28
G0 X20 Y20 Z20; this movement is not shown in the preview, as we don't know it's starting position
G1 X0            ; this is shown in preview (green indicator at the start of this preview line)
```

#### extra motion mode
This would be a bit of extra work, but we could choose to render the preview as we'd like, including the actual path the tool will take (which would require knowledge of the coordinate offsets). I'm not sure if this will really help preventing collisions, as the geometry of the setup (clamps etc.) isn't shown anyways.

----------

I've thought about going a similar route like Klipper does, handling the different WCS offsets, tool offsets, G28, canned cycles etc. in the PC software side and having GRBL always work in machine coordinates. This would enable a lot of options for doing things, eg. supporting different canned cycles and applying the height map in real-time while sending the gcode. Howeverwould introduce many new places for errors and pretty much require a rewrite. Since I can't invest that much time (and honestly, the current system works fine for 99% of all work), I'm not going that route.

> I can navigate fairly well through C# but you have a lot more depth of knowledge of the code

At least I used to 😅 Looking back, there is a lot that I would change about that code, so I can't blame you for not wanting to implement a new motion mode. I'm honestly a bit scared to touch the "inner workings" myself.

Going forward with this PR, I'd prefer not to include the system for keeping track of the offsets and G28/G30, as to implement this properly, the whole thing would need to be updated to use machine coordinates for everything.

2022-10-04 20:33 UTC, Paciente8159 commented
I guess the passthrough would work just fine and probably you should go with that to avoid complications.

As for the G92 and G54..G59.3 or canned cycles I may try to give it a try but probably will always be kind of a code reusing solution based on whatever OpenCNCPilot already does. I did plenty of C# just not WPF and sometimes I struggle with that bit. 

Currently I just have a lot on my plate with all I have planned for µCNC, and for that I won't be able to modify the code. I fully understand what you mean. I did a fair amount of rewriting on µCNC as new ideas and coding got sharper.
 
I think you can close this PR. I'll keep my fork and pick up the work later on when I find the time.
Thanks,

2022-10-13 15:10 UTC, closed without merging